trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master

jobs:
  - template: azure/msan_job.yml
    parameters:
      configurationName: DEBUG_ZTS_MSAN
      configurationParameters: '--enable-debug --enable-maintainer-zts'
      runTestsParameters: --asan
