trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/community_job.yml
    parameters:
      configurationName: COMMUNITY
      configurationParameters: >-
          --enable-debug --enable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
