trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - PHP-8.0
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - README.md
      - CONTRIBUTING.md
      - CODING_STANDARDS.md

schedules:
  - cron: "0 1 * * *"
    displayName: Nightly build
    branches:
      include:
        - PHP-7.4
        - PHP-8.0
        - master

jobs:
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_NTS
      configurationParameters: '--enable-debug --disable-zts'
  - template: azure/job.yml
    parameters:
      configurationName: RELEASE_ZTS
      configurationParameters: '--disable-debug --enable-zts'
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_DEBUG_ZTS
      configurationParameters: '--enable-debug --enable-zts'
  - template: azure/macos/job.yml
    parameters:
      configurationName: MACOS_DEBUG_NTS
      configurationParameters: '--enable-debug --disable-zts'
  - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    - template: azure/job.yml
      parameters:
        configurationName: DEBUG_ZTS
        configurationParameters: '--enable-debug --enable-zts'
    - template: azure/job.yml
      parameters:
        configurationName: RELEASE_NTS
        configurationParameters: '--disable-debug --disable-zts'
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_DEBUG_NTS
        configurationParameters: '--enable-debug --disable-zts'
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_RELEASE_NTS
        configurationParameters: '--disable-debug --disable-zts'
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_RELEASE_ZTS
        configurationParameters: '--disable-debug --enable-zts'
    - template: azure/macos/job.yml
      parameters:
        configurationName: MACOS_DEBUG_ZTS
        configurationParameters: '--enable-debug --enable-zts'
    - template: azure/macos/job.yml
      parameters:
        configurationName: MACOS_RELEASE_NTS
        configurationParameters: '--disable-debug --disable-zts'
    - template: azure/macos/job.yml
      parameters:
        configurationName: MACOS_RELEASE_ZTS
        configurationParameters: '--disable-debug --enable-zts'
    - template: azure/job.yml
      parameters:
        configurationName: DEBUG_ZTS_ASAN_UBSAN
        configurationParameters: '--enable-debug --enable-zts --enable-address-sanitizer --enable-undefined-sanitizer'
        runTestsParameters: --asan
        timeoutInMinutes: 360
    - template: azure/msan_job.yml
      parameters:
        configurationName: DEBUG_ZTS_MSAN
        configurationParameters: '--enable-debug --enable-zts'
        runTestsParameters: --msan
        timeoutInMinutes: 120
    - template: azure/community_job.yml
      parameters:
        configurationName: COMMUNITY
        configurationParameters: >-
            --enable-debug --enable-zts --enable-address-sanitizer --enable-undefined-sanitizer
            CFLAGS='-fno-sanitize-recover'
    - template: azure/coverage_job.yml
      parameters:
        configurationName: COVERAGE_DEBUG_ZTS
        configurationParameters: '--enable-debug --disable-zts'
        timeoutInMinutes: 90
    - template: azure/opcache_variation_job.yml
      parameters:
        configurationName: DEBUG_NTS_OPCACHE
        configurationParameters: '--enable-debug --disable-zts'
        timeoutInMinutes: 90
    - template: azure/job.yml
      parameters:
        configurationName: DEBUG_NTS_REPEAT
        configurationParameters: '--enable-debug --disable-zts'
        runTestsParameters: '--repeat 2'
    - template: azure/libmysqlclient_job.yml
      parameters:
        configurationName: LIBMYSQLCLIENT_DEBUG_NTS
        configurationParameters: '--enable-debug --disable-zts'
